// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGH35GlseUOkNTia_2nAZvTiQfBWeSVvs',
    appId: '1:574053615024:web:5a786799dc1ebf0baac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    authDomain: 'norskfuelpriceapp-firebase.firebaseapp.com',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
    measurementId: 'G-E2EGT74TYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDVQfY3vMsdHdaU8PXHOt6u47vu8u0ts',
    appId: '1:574053615024:android:6f97c12579939bf4aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOeBMEipFYvMCSdc7029YL_WuhGTZS82Q',
    appId: '1:574053615024:ios:c7cae6f07fb364b1aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
    androidClientId: '574053615024-3mo1ga3jb9b16sg2vjnvn4odceoij9o6.apps.googleusercontent.com',
    iosClientId: '574053615024-7of7ud6ukc19dr48lrnr387mi5t373dg.apps.googleusercontent.com',
    iosBundleId: 'no.fueltracker.fuelPriceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOeBMEipFYvMCSdc7029YL_WuhGTZS82Q',
    appId: '1:574053615024:ios:c7cae6f07fb364b1aac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
    androidClientId: '574053615024-3mo1ga3jb9b16sg2vjnvn4odceoij9o6.apps.googleusercontent.com',
    iosClientId: '574053615024-7of7ud6ukc19dr48lrnr387mi5t373dg.apps.googleusercontent.com',
    iosBundleId: 'no.fueltracker.fuelPriceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGH35GlseUOkNTia_2nAZvTiQfBWeSVvs',
    appId: '1:574053615024:web:9ae8a1676765c09caac275',
    messagingSenderId: '574053615024',
    projectId: 'norskfuelpriceapp-firebase',
    authDomain: 'norskfuelpriceapp-firebase.firebaseapp.com',
    storageBucket: 'norskfuelpriceapp-firebase.firebasestorage.app',
    measurementId: 'G-407JWBGLNH',
  );
}
